version: '3.7'
services:
    apache:
        build: .docker/apache
        container_name: arbex_apache
        ports:
            - ${HTTP_PORT}:80
        volumes:
            - .:/var/www/app:cached
        depends_on:
            - php
        networks:
            - frontend
            - backend
            - arbex_network

    mysql:
        image: mysql:latest
        container_name: arbex_mysql
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            - backend
        environment:
            MYSQL_ROOT_PASSWORD: fej7vae1Gainoo9
            MYSQL_DATABASE: arbex
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        volumes:
            - ${MYSQL_DATA_STORAGE_PATH}:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: arbex_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8081:80
        links:
            - mysql
        networks:
            - frontend
            - backend

    php:
        build:
            context: .docker/php
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
        container_name: arbex_php
        volumes:
            - .:/var/www/app:cached
        depends_on:
            - mysql
        networks:
            - backend

networks:
    frontend:
    backend:
    arbex_network:
        external: true
